### ISSUE TITLE
Unable to navigate to Scene with Actions.key

### ISSUE THREAD

**Issue by nikitph** [aksonov/react-native-router-flux#2452]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4. latest
- react-native v0.47.2

### Expected behaviour
expect ACTIONS.KEY to take me to the necessary scene.

### Actual behaviour
nothing happens. no errors i just stay stuck on the same scene. 

### Steps to reproduce
```jsx
class NavigationRouter extends Component {
  render() {
    return (
      <Router>
        {/*<Scene key='drawer' component={NavigationDrawer} open={false}>*/}
          {/*<Scene key='drawerChildrenWrapper' navigationBarStyle={Styles.navBar} titleStyle={Styles.title}*/}
                 {/*leftButtonIconStyle={Styles.leftButton} rightButtonTextStyle={Styles.rightButton}>*/}
        <Stack key="root">

        <Scene key='Dashboard' component={Dashboard} hideNavBar/>
            <Scene key='SignUpDetailsScreen' component={SignUpDetailsScreen} hideNavBar/>
            <Scene key='ResetPasswordScreen' component={ResetPasswordScreen} hideNavBar/>
            <Scene key='SignUpScreen' component={SignUpScreen} hideNavBar/>
            <Scene key='LoginScreen' component={LoginScreen} hideNavBar/>
            <Scene initial key='WalkThroughScreen' component={WalkThroughScreen} hideNavBar/>
        {/*
        </Scene>
        </Scene>*/}
        </Stack>
      </Router>
    )
  }
}

export default NavigationRouter
```

and here is where i am calling it

``` jsx
 <RectangleButton
              onPress={()=>Actions.LoginScreen}
              text="LOGIN"
              type="primary"
              height={75}
              backgroundColors={['#BF9C65', '#CEA76A']}
              gradientStart={{ x: 0.5, y: 1 }}
              gradientEnd={{ x: 1, y: 1 }}
            >
            </RectangleButton>
```
i have tried these permutations of the `onPress`:
`{() => Actions.LoginScreen}`
`{() => Actions.LoginScreen()}`
`{Actions.LoginScreen}`

So thats not the problem. one gentleman solved this by going to v3. thats not working for me

**Comment by josiahres** [comment]
I am also getting this error. Can't navigate to another scene and no error is displayed

**Comment by mcabs3** [comment]
`onPress={()=>Actions.LoginScreen}` needs to be `onPress={()=>Actions.LoginScreen()}`

**Comment by nikitph** [comment]
Did you not read my bug report. I already said i tried all variations of
function call in onPress. None of them are working. This bug should not be
closed

**Comment by mcabs3** [comment]
you said you tried {ACTIONS.LoginScreen()}, that isn't the same as {() => Actions.LoginScreen()}

**Comment by nikitph** [comment]
"i have tried all permuatations of the call in bold (
{ACTIONS.LoginScreen}, {ACTIONS.LoginScreen()} etc"

So yes your suggestion has been tried and it does not work.

**Comment by mcabs3** [comment]
What Scene are you at trying to navigate to `LoginScreen`?

**Comment by mcabs3** [comment]
I have updated your description of the problem to better explain your situation, please review it when you have a moment.

**Comment by josiahres** [comment]
I also get this issue. Before it worked fine on React-native-router-flux 3.38. I then updated to the latest version of react-native-router-flux and now as mentioned in this open issue, I can't change scenes using ACTIONS.KEY. I tried with RN 0.48.3 and 0.48.4 and I get the same issue

**Comment by karanwadhwa** [comment]
I've been facing a similar issue. 
`    <Router>
      <Scene key="root" hideNavBar>

        {/* Authentication Bucket */}
        <Scene key="auth" >
          <Scene key="login" component={LoginForm} title="ManagerLogin" initial />
        </Scene>

        {/* Main Bucket */}
        <Scene key="main" >
          <Scene 
            rightTitle=" Add"
            onRight={() => Actions.AddEmployee()} 
            key="employeeList" 
            component={EmployeeList} 
            title="Employee List" 
            initial
          />
          <Scene key="addEmloyee" component={AddEmployee} title="Add Employee" />  
        </Scene>

         {/* Test Bucket */}
        <Scene key="moo" >
          <Scene key="add" component={AddEmployee} title="Add Employee" />  
          <Scene key="emp" component={EmployeeList} title="Employee" />
        </Scene>

      </Scene>
    </Router>`

in the above code when I click on `rightTitle` it gives me the following error: `undefined is not a function (evaluating '_reactNativeRouterFlux.Actions.addEmployee()')


------ Case2:
when I call `Action.key` directly from the body like so:
`<Text onPress={Actions.moo}>EmployeeList</Text>`
it works perfectly and navigates to the first scene in the 'moo' scene.
but if i change it to `<Text onPress={() => Actions.moo()}>EmployeeList</Text>` it doesn't work

------Case 2.1:
similarly, if I want to access the `addEmployee` nested within `moo` neither of the options below work:
`<Text onPress={Actions.addEmployee}>EmployeeList</Text>`
`<Text onPress={() => Actions.addEmployee()}>EmployeeList</Text>`

------ Case 3:
`Actions.key()` works fine in this scenario:
`firebase.auth().signInWithEmailAndPassword(email, password)
      .then(user => {
        dispatch({ type: LOGIN_USER_SUCCESS, payload: user });
        Actions.main();
      })`

------
P.S. i only get an error when i add Actions.key to onRight whereas there's simply no response in other cases.
I might be wrong and probably theres nothing broken in RNRF but i just cant seem to figure this out.

**Comment by mcabs3** [comment]
@karanwadhwa the error you are getting for the onRight is because of the key for that `Scene` is `add` not `addEmployee`

**Comment by schlaegerz** [comment]
I am having the same problem. Happened when I tried to move to the beta since 3.38 does not work on RN 0.49

**Comment by aksonov** [comment]
Please read docs for v4 - you should not have both `component` and children defined. Your 'Dashboard' is considered as child, not container.

**Comment by karanwadhwa** [comment]
hey @aksonov that doesn't solve my issue. I don't have component defined in my container.

**Comment by aksonov** [comment]
Do you mean wrongly typed Actions.AddEmployee()  ?

**Comment by karanwadhwa** [comment]
AddEmployee is the component name while `addEmployee` is the key so `Actions.addEmployee()` should work but it doesnt.

**Comment by aksonov** [comment]
You tried another action staring with uppercase

**Comment by karanwadhwa** [comment]
no i didnt. please refer to this

> I've been facing a similar issue. 
```jsx
      <Router>
      <Scene key="root" hideNavBar>

        {/* Authentication Bucket */}
        <Scene key="auth" >
          <Scene key="login" component={LoginForm} title="ManagerLogin" initial />
        </Scene>

        {/* Main Bucket */}
        <Scene key="main" >
          <Scene 
            rightTitle=" Add"
            onRight={() => Actions.AddEmployee()} 
            key="employeeList" 
            component={EmployeeList} 
            title="Employee List" 
            initial
          />
          <Scene key="addEmloyee" component={AddEmployee} title="Add Employee" />  
        </Scene>

         {/* Test Bucket */}
        <Scene key="moo" >
          <Scene key="add" component={AddEmployee} title="Add Employee" />  
          <Scene key="emp" component={EmployeeList} title="Employee" />
        </Scene>

      </Scene>
    </Router>
```

in the above code when I click on `rightTitle` it gives me the following error: `undefined is not a function (evaluating '_reactNativeRouterFlux.Actions.addEmployee()')


------ 
Case2:
when I call `Action.key` directly from the body like so:
`<Text onPress={Actions.moo}>EmployeeList</Text>`
it works perfectly and navigates to the first scene in the 'moo' scene.
but if i change it to `<Text onPress={() => Actions.moo()}>EmployeeList</Text>` it doesn't work

------
Case 2.1:
similarly, if I want to access the `addEmployee` nested within `moo` neither of the options below work:
`<Text onPress={Actions.addEmployee}>EmployeeList</Text>`
`<Text onPress={() => Actions.addEmployee()}>EmployeeList</Text>`

------ 
Case 3:
`Actions.key()` works fine in this scenario:
`firebase.auth().signInWithEmailAndPassword(email, password)
      .then(user => {
        dispatch({ type: LOGIN_USER_SUCCESS, payload: user });
        Actions.main();
      })`

------
P.S. i only get an error when i add Actions.key to onRight whereas there's simply no response in other cases.
I might be wrong and probably theres nothing broken in RNRF but i just cant seem to figure this out.

**Comment by bushev** [comment]
Have a similar problem.

**Comment by sitompul** [comment]
This also occurred to me. Somehow, the Actions.key-name stop working. But not all of them are affected. Error trace returns 
```
[TypeError: undefined is not a function (evaluating '_this3[type](routeName, res)')]
```

**Comment by renatofilipov** [comment]
I also get the same issue... when I run the "demo app", it works. But when I import to my working (ejected) app, it doesn't.

Any hints?

Thanks!

**Comment by jeovanymosh** [comment]
@karanwadhwa did you solved this?

**Comment by renatofilipov** [comment]
Yes, I have just solved it. Thanks!

Em 5 de dez de 2017 18:16, "Jeovany" <notifications@github.com> escreveu:

**Comment by gagantaneja** [comment]
Running into exactly same issue . It ran smoothly for me earlier with the same code but when i created a new project with the same code, it stopped working on some places . Please do help.

**Comment by preetampatil3d** [comment]
Any status on this issue?

**Comment by gagantaneja** [comment]
This is an issue with the latest update of the library. Trying adding both the scenes under the same parent scene. If both of them exist under different scenes. Try : Actions.parentKey; Actions.scene

**Comment by preetampatil3d** [comment]
It worked . . 
Old code :
 ` onPress={() => { Actions.map() }}`
Modified code :
`  onPress={() => { Actions.menu();Actions.map() }}`


Thanks lot @gagantaneja

**Comment by hussein661** [comment]
use `Actions.anotherPage `instead of `Actions.anotherPage()`

**Comment by paulofagnerdeoliveira** [comment]
eu não conseguir chamar a função do meu botão

**Comment by manhhoan73** [comment]
> use `Actions.anotherPage `instead of `Actions.anotherPage()`

thank a lot
