### ISSUE TITLE
(0, _reactNavigation.withOrientation) is not a function. (In '(0, _reactNavigation.withOrientation)(Header)', '(0, _reactNavigation.withOrientation)' is undefined)

### ISSUE THREAD

**Issue by Arwiz** [aksonov/react-native-router-flux#3216]
### Version
Tell us which versions you are using: 
4.0.0-beta.27

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native ~0.51.0

### Expected behaviour
It was a working project now the application is not responding with these errors.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by daviscabral** [comment]
There is no way to help with the information provided here. Please fill the information from the template.

**Comment by daviscabral** [comment]
@ptmaroct thank you.

**Comment by nagacoder** [comment]
some problem with me

**Comment by daviscabral** [comment]
Please provide a https://stackoverflow.com/help/mcve or enough information to reproduce this error. Closing this issue for the lack of information by all the users that complained about it since it was opened.

**Comment by marcoj** [comment]
same here, just updated to 4.0.1

**Comment by abrantes01** [comment]
I was facing the same issue after upgrading to 4.0.1. Just restarting packager and rebuilding the app and everything is fine.

**Comment by QingYong** [comment]
I fixed it by upgrade react-navigation > 2.0.0 
With react native version of 0.51

**Comment by michaelVictoriaDev** [comment]
same problem :(

from "^3.43.0"
