### ISSUE TITLE
 typeError: navigationStore.getStateForAction is not a function

### ISSUE THREAD

**Issue by teilala** [aksonov/react-native-router-flux#3296]
**in examples/react-native**

"dependencies": {
    "@babel/runtime": "^7.0.0",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-button": "^2.3.0",
    "react-native-message-bar": "^2.0.10",
    "react-native-router-flux": "^4.0.3",
    "react-native-screens": "^1.0.0-alpha.12",
    "react-navigation": "2.16.x",
    "react-navigation-deprecated-tab-navigator": "^1.3.0",
    "react-navigation-stack": "^0.6.0"
  },

always get this error
###  typeError: navigationStore.getStateForAction is not a function
![2018-09-27 10 19 16](https://user-images.githubusercontent.com/4106105/46119966-2b014880-c240-11e8-8775-bbe3df9ec68b.png)

**Comment by aksonov** [comment]
Should be fixed with 4.0.4

**Comment by RtzX** [comment]
me too.version: 4.0.4!

<img width="443" alt="qq20180929-093705 2x" src="https://user-images.githubusercontent.com/13709644/46239443-55cbd800-c3cb-11e8-93bf-f66448eeccde.png">

code:
<img width="863" alt="qq20180929-094037 2x" src="https://user-images.githubusercontent.com/13709644/46239486-c4109a80-c3cb-11e8-90f1-ecc225356451.png">

**Comment by daviscabral** [comment]
@aksonov this seems still broken - the old API was not passing `navigationStore` but `params`.

**Comment by aksonov** [comment]
Could you fix it by removing of navigationStore as param at all?

**Comment by aksonov** [comment]
Please check 4.0.5 version

**Comment by haorh** [comment]
When migrating from v3 to v4.0.6, the solution for me was
```javascript
import { combineReducers } from 'redux';
import NormalReducer from './normal-reducer';
import RouteReducer from './route-reducer';

const appReducer = combineReducers({
    normal: NormalReducer,
    route: RouteReducer
});
export default (state, action) => {
    return appReducer(state, action);
}
```
change the bottom code
```javascript
export default (state, action) => {
    return appReducer;
}
```

**Comment by vonwao** [comment]
I'm getting this error, for 4.0.6.  I wonder what could be the cause

**Comment by ahsan-viabletree** [comment]
any update?

**Comment by gghnisan** [comment]
4.2.0, 4.3.0, the same.

**Comment by aliustaoglu** [comment]
Hmm this started happening to me after I upgraded RN 0.63.4 to RN 0.64.0

**Comment by ahsan-abrar** [comment]
here is a quick fix, downgrade react-native-router-flux to  react-native-router-flux": "4.0.0-beta.27" and run these commands

watchman watch-del-all
yarn cache clean --force
npm cache clean --force # optional - in case you also have used npm
rm -rf node_modules/
rm yarn.lock
rm package-lock.json # optional - in case you also have used npm
rm -rf $TMPDIR/metro-*
rm -rf $TMPDIR/haste-*
yarn 
yarn start --reset-cache

reference:
https://github.com/aksonov/react-native-router-flux/issues/3023

**Comment by sherxia92** [comment]
when upgrad react-native-route-flux.
``<Router createReducer={reducerCreate} backAndroidHandler={this.onBackPress.bind(this)} panHandlers={this.panResponder()}>``
should be remove attribute ``createReducer`` and ``panHandlers``
like this
``<Router backAndroidHandler={this.onBackPress.bind(this)}>``
