### ISSUE TITLE
Error on ios platform

### ISSUE THREAD

**Issue by dalba1992** [aksonov/react-native-router-flux#3294]
### Version

- react-native-router-flux v4.0.3
- react v16.4.2
- react-native v0.55.4

### Actual behaviour
![image](https://user-images.githubusercontent.com/20521231/46075763-10868b00-c1be-11e8-9ddd-ea1e0072c0fb.png)

**Comment by alprtv** [comment]
I have the same error when upgrading from 4.0.1 to 4.0.3
```
TypeError: navigationStore.getStateForAction is not a function. (In 'navigationStore.getStateForAction(action, state)', 'navigationStore.getStateForAction' is undefined)

This error is located at:
    in NavigationContainer (at Router.js:97)
    in App (at Router.js:122)
```

**package.json**
```
"react": "16.5.2",
"react-native": "0.57.1",
"react-native-router-flux": "^4.0.3",
```

Version 4.0.1  is work fine. I'll try install 4.0.2 and write feedback

**Comment by aksonov** [comment]
Probably you have custom reducer, so you need now to pass Actions to createReducer method.
Please check Example project for more details.

**Comment by dalba1992** [comment]
It was working well on android, but it is not working on only ios

**Comment by aksonov** [comment]
Please check examples/react-native - it works for iOS

**Comment by MaxInMoon** [comment]
If your app breaks after upgrading to > 4.0.2, you should maybe re-consider your router declaration when app starts, as done [here in the example](https://github.com/aksonov/react-native-router-flux/blob/master/examples/react-native/Example.js)

**Comment by daviscabral** [comment]
There was a change in the `createReducer` API like you can see in the image below.

<img width="546" alt="screenshot 2018-09-26 18 15 00" src="https://user-images.githubusercontent.com/4285/46109888-43c61b80-c1b8-11e8-88e1-79e11de699e3.png">

PR #3295 shows the change in the expo example.

**Comment by aksonov** [comment]
My apologies for breaking change. I mistakenly thought that `createReducer` is not used ;)
4.0.4 should fix it - old API is preserved

**Comment by ebaynaud** [comment]
@aksonov still getting this error when running examples/react-native on ios with 4.0.6

**Comment by shiqkuangsan** [comment]
@aksonov me too, still getting this error when running examples/react-native on ios with V4.0.6

**Comment by ahsan-abrar** [comment]
here is a quick fix, downgrade react-native-router-flux to  react-native-router-flux": "4.0.0-beta.27" and run these commands

watchman watch-del-all
yarn cache clean --force
npm cache clean --force # optional - in case you also have used npm
rm -rf node_modules/
rm yarn.lock
rm package-lock.json # optional - in case you also have used npm
rm -rf $TMPDIR/metro-*
rm -rf $TMPDIR/haste-*
yarn 
yarn start --reset-cache

reference:
https://github.com/aksonov/react-native-router-flux/issues/3023
